# Generated by Django 4.0.3 on 2022-03-07 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby_name', models.CharField(max_length=20)),
                ('baby_description', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_name', models.CharField(max_length=30)),
                ('champion_description', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Rookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rookie_name', models.CharField(max_length=30)),
                ('rookie_description', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.attribute')),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_name', models.CharField(max_length=20)),
                ('training_description', models.TextField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.attribute')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.stage')),
                ('typ', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.type')),
            ],
        ),
        migrations.CreateModel(
            name='Third',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.champion')),
                ('rookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.rookie')),
            ],
        ),
        migrations.CreateModel(
            name='Second',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rookie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.rookie')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.training')),
            ],
        ),
        migrations.AddField(
            model_name='rookie',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.stage'),
        ),
        migrations.AddField(
            model_name='rookie',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.type'),
        ),
        migrations.CreateModel(
            name='First',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.baby')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.training')),
            ],
        ),
        migrations.AddField(
            model_name='champion',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.stage'),
        ),
        migrations.AddField(
            model_name='champion',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.type'),
        ),
        migrations.AddField(
            model_name='baby',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.stage'),
        ),
        migrations.AddField(
            model_name='baby',
            name='typ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsters.type'),
        ),
    ]
